---
title: "Codebook"
author: "Amey Kokane"
date: "September 17, 2016"
output: html_document
---

#Abstract
Human Activity Recognition database built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.

- Data Set Characteristics: Multivariate, Time-Series

- Number of Instances: 10299

- Number of Attributes: 561

- Number of Classes: 6

#Dataset Information:
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. 

Check the README.txt file for further details about this dataset.

A video of the experiment including an example of the 6 recorded activities with one of the participants can be seen in the following link: http://www.youtube.com/watch?v=XOEN9W05_4A

#Atribute Information:
For each record in the dataset it is provided:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration. 

- Triaxial Angular velocity from the gyroscope. 

- A 561-feature vector with time and frequency domain variables. 

- Its activity label. 

- An identifier of the subject who carried out the experiment.

# Steps used in Data trasnformation

## Import appropriate data files in R and Merge Train and Test data files

From all the files provided in UCI HAR Dataset folder we are interested in: 

SUBJECT FILES

-test/subject_test.txt

-train/subject_train.txt


ACTIVITY FILES

-test/y_test.txt

-train/y_train.txt


-activity_labels.txt - Links the class labels with their activity name.

DATA FILES (experiment data)

-test/X_test.txt

-train/X_train.txt


-features.txt - Names of column variables in the data

There are 10299 rows for all the datasets that have been created by combining resp Train and Test datasets.

##Renaming variables for combined  DATA (experiment data)
Use features.txt file to replace the variable names for combined experiment data

## Extract Mean() and Std() variables 
From the merged Data set create a subset data set that only includes variables are for mean and std.

This data set contains 10299 rows and 68 cols

## Change descriptive activity numbers with names for the activities in the data set
Use the activity_label.txt file to add the Activity Names in the data file.

This will add one more col making number if cols = 69

## Aggregate the data table for average of each Activity for each subject
Creates a summarized data that averages the original data by each Activity for each Subject

In this step 10299 instances are grouped into  180 groups (30 subjects * 6 activities) and average is calculate for 66 mean and sd columns for these groups.  

## Appropriately label the data set with descriptive variable names.
1.prefix t is replaced by time

2.Acc is replaced by Accelerometer

3.Gyro is replaced by Gyroscope

4.prefix f is replaced by frequency

5.Mag is replaced by Magnitude

6.BodyBody is replaced by Body
 
7. mean() is replaced by MEAN

8. std() is replaced by SD

## Write tidy data file to drive

The tidy data is a dataset with 180 rows and 69 columns
